ALTER DATABASE [PROIECT] ADD FILEGROUP [NewFG]

ALTER DATABASE [PROIECT]
ADD FILE ( NAME = N'Fisier1',
FILENAME = N'D:\ATM\ANUL_2\SEM2\BAZE DE DATE\Proiect_EU_2021\Fisier1.ndf',
SIZE = 4096KB,
FILEGROWTH = 1024000KB ),
( NAME = N'Fisier2',
FILENAME = N'D:\ATM\ANUL_2\SEM2\BAZE DE DATE\Proiect_EU_2021\Fisier2.ndf',
SIZE = 4096KB,
FILEGROWTH = 1024000KB ),
( NAME = N'Fisier3',
FILENAME = N'D:\ATM\ANUL_2\SEM2\BAZE DE DATE\Proiect_EU_2021\Fisier3.ndf',
SIZE = 4096KB,
FILEGROWTH = 1024000KB )
TO FILEGROUP [NewFG]

ALTER DATABASE [PROIECT]
ADD LOG FILE 
(
	Name = Log1,
FileName = 'D:\ATM\ANUL_2\SEM2\BAZE DE DATE\Proiect_EU_2021\Log1.ldf',
size = 10MB, -- KB, Mb, GB, TB
maxsize = unlimited,
filegrowth = 1024MB
)
ALTER DATABASE [PROIECT]
ADD LOG FILE 
(
	Name = Log2,
FileName = 'D:\ATM\ANUL_2\SEM2\BAZE DE DATE\Proiect_EU_2021\Log2.ldf',
size = 10MB, -- KB, Mb, GB, TB
maxsize = unlimited,
filegrowth = 1024MB
)
BACKUP DATABASE PROIECT
TO DISK = 'D:\ATM\ANUL_2\SEM2\BAZE DE DATE\Proiect_EU_2021\BackupPROIECT.bak'
WITH init, format, stats = 10
