USE [PROIECT]
GO

/****** Object:  Table [dbo].[Judete]    Script Date: 5/12/2021 8:00:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Judete](
	[IdJudet] [int] IDENTITY(1,1) NOT NULL,
	[NumeJudet] [nvarchar](64) NOT NULL,
 CONSTRAINT [PK_Regiuni] PRIMARY KEY CLUSTERED 
(
	[IdJudet] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


